AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless URL Shortener

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12
    Environment:
      Variables:
        TABLE_NAME: !Ref UrlTable

Resources:
  # DynamoDB Table
  UrlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: url-shortener
      AttributeDefinitions:
        - AttributeName: short_code
          AttributeType: S
      KeySchema:
        - AttributeName: short_code
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  # Create URL Lambda Function
  CreateUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: url-shortener-create
      CodeUri: create-url/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlTable
      Events:
        CreateApi:
          Type: Api
          Properties:
            Path: /create
            Method: post
            RestApiId: !Ref UrlShortenerApi

  # Redirect URL Lambda Function
  RedirectUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: url-shortener-redirect
      CodeUri: redirect-url/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlTable
      Events:
        RedirectApi:
          Type: Api
          Properties:
            Path: /r/{short_code}
            Method: get
            RestApiId: !Ref UrlShortenerApi

  # Explicit API Gateway definition
  UrlShortenerApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${UrlShortenerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  CreateUrlEndpoint:
    Description: "Endpoint for creating short URLs"
    Value: !Sub "https://${UrlShortenerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create"